### ISSUE TITLE
Missing arjunacore's parent in urlmap result

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/cartographer#109]
There is a missing parent artifact in urlmap result.
The root artifact is org.overlord.rtgov.samples.jbossas.ordermgmt:samples-jbossas-ordermgmt-app:2.0.3.Final-redhat-1, preset is build-requires and there are 2 relationship paths leading through org.jboss.as:jboss-as-build:7.5.7.Final-redhat-3 after that the paths look like this (only artifactIds)
* jboss-as-build => jbossxts => arjunacore
* jboss-as-build => jboss-as-xts => jbosstxbridge => jbossxts => arjunacore

The problem is that dependency management in jboss-as-build's parent (jboss-as-parent) declares jbossxts dependency with exclusion of several artifacts and arjunacore amongst them. The problem is that the dependency management gets used only in the first path but in the second path it uses depMgmt record for jboss-as-xts, which does not declare any exclusions. With the first path the relationship to arjunacore gets recorded in the graph DB, but is not accepted by the filter because of the exclusion. When it gets to jbosstxbridge, it does not add jbossxts to todos, because it was recorded as already seen and subsequently no further relationships of arjunacore get examined even though the relationship would be accepted in this path.
When collecting the urlmap result, it finds a path leading to arjunacore that is accepted by a filter, so it gets included, but there are missing artifacts referenced in its pom, at least arjunacore-all, which is its parent.
When I retried to run the same request multiple times on the same workspace, sometimes it happened that arjunacore-all started to be returned in the result, but not sure how I achieved that.

**Comment by pkocandr** [comment]
I wonder if there is a better solution than recording the seen artifacts with exclusions (if possible) and make them part of the DiscoveryTodo.equals() comparison.

**Comment by jdcasey** [comment]
So you're talking about adding the exclusions to the DiscoveryTodo.equals() calculation, basically? That sounds like a good solution to me, since it would distinguish two different use cases of the same artifact. I'm not sure about including the seen artifacts themselves (if that's what you're saying) since then the only way two DiscoveryTodo's would be equal would be if they had the exact same path (which would probably only happen if there was some sort of cycle, and even then only sub-paths would match).

This is an optimization problem, but I think we have to be careful about allowing too many instances of DiscoveryTodo (making equals too restrictive), since this could have a dramatic effect on the speed of the graph discovery.

**Comment by pkocandr** [comment]
I meant only adding the exclusions to the DiscoveryTodo.equals().
Regarding optimization is there any good reason to traverse inherited relationships in urlmap, paths and maybe more methods? I think it would make the methods faster, maybe not the graph construction because of the seen mechanism, but at least the collection of the result. I believe they are in the DB just to be able to read all relationships along with the inherited ones easily, right?

**Comment by pkocandr** [comment]
This was (mostly) fIxed by PR #110
